# Activa el perfil dev en local
spring.profiles.active=dev

# --- Base de Datos ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=update

# --- JWT ---
jwt.secret=${JWT_SECRET}

# --- Google OAuth ---
google.oauth.client-id=${GOOGLE_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_CLIENT_SECRET}
google.oauth.refresh-token=${GOOGLE_REFRESH_TOKEN}
google.oauth.email-from=${GOOGLE_EMAIL_FROM}

# --- Swagger ---
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# --- Puerto ---
server.port=${PORT:8080}